export const CONFIG = {
    background: "#0a0a2e",
    ship: {
        color: 0x4da6ff,
        coreColor: 0xffffff,
        radius: 20,
        coreRadius: 5,
        coreOffsetY: -5,
        vertices: [0, -20, -15, 10, 15, 10],
    },
    asteroid: {
        fill: 0x888888,
        stroke: 0xcccccc,
        strokeWidth: 1,
        radiusMin: 15,
        radiusMax: 35,
        segmentsMin: 7,
        segmentsMax: 11,
        baseSpeedMin: 2,
        baseSpeedMax: 5,
        rotationSpeedMin: -0.05,
        rotationSpeedMax: 0.05,
    },
    particle: {
        alpha: 0.9,
        decay: 0.02,
        radiusMin: 1,
        radiusMax: 4,
    },
    engine: {
        color: 0xff6600,
        alpha: 0.9,
        decay: 0.02,
        radiusMin: 1,
        radiusMax: 4,
        vxRange: 0.75,
        vyBaseMin: 2,
        vyBaseMax: 4,
    },
    explosion: {
        color: 0xff4444,
        alpha: 1,
        decay: 0.025,
        radiusMin: 2,
        radiusMax: 6,
        speedMin: 2,
        speedMax: 4,
        count: 20,
    },
    difficulty: {
        initialSpawnRate: 0.02,
        spawnRateIncrease: 0.001,
        speedIncrease: 0.1,
        maxSpawnRate: 0.06,
        maxSpeedBonus: 3,
    },
    scorePerAsteroid: 10,
    styles: {
        score: { fontSize: 24, fill: "#ffffff", fontFamily: "Arial" },
        gameOver: { fontSize: 32, fill: "#ff4444", fontFamily: "Arial", align: "center" },
        record: { fontSize: 24, fill: "#ffaa00", fontFamily: "Arial", align: "center" },
        startPrompt: { fontSize: 28, fill: "#ffffff", fontFamily: "Arial", align: "center" },
    },
};